# Generated by Django 4.0.5 on 2022-06-19 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0003_alter_task_planned_comp_dt_taskfiles'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TaskFiles',
            new_name='TaskFile',
        ),
    ]
