# Generated by Django 4.0.5 on 2022-06-22 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0006_rename_creator_task_user_remove_task_executor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.IntegerField(choices=[(0, 'created'), (1, 'active'), (2, 'completed')], default=0),
        ),
    ]
