# Generated by Django 4.0.5 on 2022-06-20 21:03

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0002_profile_company_profile_user_profile_user_photo_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SocialLinks',
            new_name='SocialLink',
        ),
    ]
